apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-admission-controller
spec:
  template:
    metadata:
      labels:
        tier: app
    spec:
      securityContext:
        runAsUser: 65534
