bases:
- github.com/ticketmaster/vertical-pod-autoscaler-config//base

commonLabels:
  app: vertical-pod-autoscaler
  inventoryCode: vertical-pod-autoscaler
  productCode: prd354

namespace: prd354

patches:
- admission-controller-deployment.yaml
- recommender-deployment.yaml
- updater-deployment.yaml

patchesJson6902:
- path: admission-controller-deployment.json
  target:
    version: v1
    group: apps
    kind: Deployment
    name: vpa-admission-controller
- path: recommender-deployment.json
  target:
    version: v1
    group: apps
    kind: Deployment
    name: vpa-recommender
- path: updater-deployment.json
  target:
    version: v1
    group: apps
    kind: Deployment
    name: vpa-updater

resources:
- servicemonitors.yaml
- services.yaml
- tls-certs-secret.yaml
